included:
  - HazeLight
  - HazeLightTests
  - HazeLightUITests
excluded:
  - Pods
disabled_rules:
  - file_length
  - force_cast
  - force_try
  - function_body_length
  - function_parameter_count
  - identifier_name
  - line_length
  - nesting
  - notification_center_detachment
  - todo
  - trailing_whitespace
  - type_body_length
  - type_name
opt_in_rules:
  - closure_end_indentation
  - closure_spacing
  - empty_count
  - explicit_init
  - fatal_error_message
  - first_where
  - for_where
  - joined_default_parameter
  - let_var_whitespace
  - multiline_parameters
  - number_separator
  - operator_usage_whitespace
  - overridden_super_call
  - prohibited_super_call
  - redundant_nil_coalescing
  - sorted_first_last
  - sorted_imports
  - trailing_closure
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
